version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - nginx
    environment:
      - PORT=8080
      - YDB_CONNECTIONSTRING=test
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./configs/test/nginx.conf:/etc/nginx/nginx.conf
      - ./testdata:/usr/share/nginx/html
    restart: unless-stopped
