
@feedSourceId = 0939a891-f54e-4697-b600-3e01b1eceac1

### Add feed source
POST {{url}}/api/feed-sources
X-UserId: {{userId}}
Content-Type: application/json

{
  "name": "opennet",
  "feed_url": "https://www.opennet.ru/opennews/opennews_all.rss",
  "disabled": false
}

### Get feed sources
GET {{url}}/api/feed-sources
X-UserId: {{userId}}

### Get feed source by id
GET {{url}}/api/feed-sources/{{feedSourceId}}
X-UserId: {{userId}}

### Update feed source
PATCH {{url}}/api/feed-sources/{{feedSourceId}}
X-UserId: {{userId}}
Content-Type: application/json

{
  "disabled": true
}

### Delete feed source id
DELETE {{url}}/api/feed-sources/{{feedSourceId}}
X-UserId: {{userId}}
